app/main/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, PasswordField, \
    SelectField, SelectMultipleField, TextAreaField, RadioField
from wtforms.validators import DataRequired, Length
from wtforms import ValidationError
from ..models import User, Topic, Question
from flask_pagedown.fields import PageDownField

class EditProfileForm(FlaskForm):
    username = StringField(u'用户名')
    gender = RadioField(u'性别', choices=[('Male', u'男'), ('Female', u'女')])
    description = StringField(u'一句话介绍')
    location = StringField(u'居住地')
    profession = StringField(u'所在行业')
    working_experience = TextAreaField(u'职业经历')
    education_experience = TextAreaField(u'教育经历')
    about_me = TextAreaField(u'个人简介')
    submit = SubmitField(u'提交')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.user = user

    def validate_username(self, field):
        if field.data != self.user.username and \
            User.query.filter_by(username=field.data).first():
            raise ValidationError(u'该用户名已存在')

class AddTopicForm(FlaskForm):
    name = StringField(u'话题名称', validators=[DataRequired(), Length(1, 64)])
    description = TextAreaField(u'话题描述', validators=[DataRequired()])
    submit = SubmitField(u'提交')

    def validate_name(self, field):
        if Topic.query.filter_by(name=field.data).first():
            raise ValidationError(u'话题已存在！')

class AskingForm(FlaskForm):
    title = StringField(u'问题标题', validators=[DataRequired()])
    topics = SelectMultipleField(u'添加话题-可以多选（ctrl）', coerce=int, validators=[DataRequired()])
    body = TextAreaField(u'问题描述,可选')
    submit = SubmitField(u'提交问题')

    def __init__(self, *args, **kwargs):
        super(AskingForm, self).__init__(*args, **kwargs)
        self.topics.choices = [(topic.id, topic.name)
                               for topic in Topic.query.order_by(Topic.name).all()]

    def validate_title(self,field):
        if Question.query.filter_by(title=field.data).first():
            raise ValidationError(u'该问题已存在！')

class AnswerForm(FlaskForm):
    body = PageDownField(u'写回答--Markdown编辑器', validators=[DataRequired()])
    submit = SubmitField(u'提交答案')

class CommentForm(FlaskForm):
    body = TextAreaField(u'评论', validators=[DataRequired()])
    submit = SubmitField(u'评论')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms, errors

app/main/views.py
#!/usr/bin/env python
# -*-coding:utf-8 -*-

from flask import render_template, flash, redirect, url_for, abort, \
    make_response,request, current_app, g
from flask_login import login_required, current_user
from flask_sqlalchemy import get_debug_queries
from . import main
from .. import login_manager, db
from ..models import User, Topic, Question, Answer, Comment, Permission, Like
from .forms import EditProfileForm, AddTopicForm, AskingForm, AnswerForm, \
    CommentForm
from ..decorators import permission_required, admin_required
from datetime import datetime, timedelta

question_views = 0

#请求结束时调用，把查询时间超过限定值的SQL语句记录日志
@main.after_app_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= current_app.config['ZHIHU_SLOW_DB_QUERY_TIME']:
            current_app.logger.warning('Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n'
                % (query.statement, query.parameters, query.duration,
                   query.context))
    return response

#首页；根据cookies判断要看的内容和页数
@main.route('/')
def index():
    choice = int(request.cookies.get('choice', '3'))
    if not current_user.is_authenticated:
        choice = 3
    page = int(request.cookies.get('page', '1'))
    if choice == 2:
        answers = []
        pagination = current_user.likes_followings.\
            paginate(page, per_page=10, error_out=False)
        likes = pagination.items
    elif choice == 1:
        pagination = current_user.answers_followings.\
            paginate(page, per_page=10, error_out=False)
        answers = pagination.items
        likes = []
    elif choice == 0:
        pagination = current_user.answers_interested_topics.\
            paginate(page, per_page=10, error_out=False)
        answers = pagination.items
        likes = []
    else:
        pagination = Answer.query.order_by(Answer.likes_count).\
            paginate(page, per_page=10, error_out=False)
        answers = pagination.items
        likes = []
    return render_template('index.html', answers=answers,
                    likes=likes,choice=choice, pagination=pagination)

@main.route('/answers-interested-topics')
@login_required
def show_answers_interested_topics():
    PageNum = request.args.get('page', 1, type=int)
    resp = make_response(redirect(url_for('.index',)))
    resp.set_cookie('choice', '0', max_age=30 * 24 * 60 * 60)
    resp.set_cookie('page', str(PageNum))
    return resp

@main.route('/answers-followings')
@login_required
def show_answers_followings():
    PageNum = request.args.get('page', 1, type=int)
    resp = make_response(redirect(url_for('.index')))
    resp.set_cookie('choice', '1', max_age=30 * 24 * 60 * 60)
    resp.set_cookie('page', str(PageNum))
    return resp

@main.route('/likes-followings')
@login_required
def show_likes_followings():
    PageNum = request.args.get('page', 1, type=int)
    resp = make_response(redirect(url_for('.index')))
    resp.set_cookie('choice', '2', max_age=30 * 24 * 60 * 60)
    resp.set_cookie('page', str(PageNum))
    return resp

@main.route('/all-answers')
def show_all():
    PageNum = request.args.get('page', 1, type=int)
    resp = make_response(redirect(url_for('.index')))
    resp.set_cookie('choice', '3', max_age=30 * 24 * 60 * 60)
    resp.set_cookie('page', str(PageNum))
    return resp

#个人页面，默认为个人的点赞动态
@main.route('/people/<username>/activities')
@login_required
def profile(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    pagination = user.personal_likes.paginate(page, per_page=10, error_out=False)
    likes = pagination.items
    return render_template('main/profile_activities.html',
                           pagination=pagination,user=user, likes=likes)

#个人回答集合
@main.route('/people/<username>/answers')
@login_required
def people_answers(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    pagination = user.personal_answers.paginate(page, per_page=10, error_out=False)
    answers = pagination.items
    return render_template('main/profile_answers.html',
                           pagination=pagination,user=user, answers=answers)

#个人提问集合
@main.route('/people/<username>/asks')
@login_required
def people_asks(username):
    user = User.query.filter_by(username=username).first_or_404()
    asks = user.personal_questions_asked
    return render_template('main/profile_asks.html', user=user, asks=asks)

#关注的用户
@main.route('/people/<username>/followerings')
@login_required
def followings(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('main/followings.html', user=user)

#关注该用户的人
@main.route('/people/<username>/followers')
@login_required
def followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('main/followers.html', user=user)

#关注的话题
@main.route('/people/<username>/following/topics')
@login_required
def people_following_topics(username):
    user = User.query.filter_by(username=username).first_or_404()
    topics = user.topics
    return render_template('main/profile_topics.html', user=user, topics=topics)

#关注的问题
@main.route('/people/<username>/following/questions')
@login_required
def people_following_questions(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    pagination = user.questions_following.order_by(
        Question.timestamp.desc()).paginate(page, per_page=15, error_out=False)
    questions = pagination.items
    return render_template('main/profile_questions.html',
                pagination=pagination, user=user, questions=questions)

#编辑个人资料
@main.route('/people/edit', methods=['GET', 'POST'])
@login_required
def editprofile():
    form = EditProfileForm(current_user)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.gender = form.gender.data
        current_user.description = form.description.data
        current_user.location = form.location.data
        current_user.profession = form.profession.data
        current_user.working_experience = form.working_experience.data
        current_user.education_experience = form.education_experience.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        db.session.commit()
        flash(u'个人资料已更新')
        return redirect(url_for('main.profile', username=current_user.username))
    form.username.data = current_user.username
    form.gender.data = current_user.gender
    form.description.data = current_user.description
    form.location.data = current_user.location
    form.profession.data = current_user.profession
    form.working_experience.data = current_user.working_experience
    form.education_experience.data = current_user.education_experience
    form.about_me.data = current_user.about_me
    return render_template('main/editprofile.html', form=form)

#话题广场，包含网站所有话题
@main.route('/topics')
@login_required
def topic_square():
    topics = Topic.query.all()
    return render_template('topic_square.html', topics=topics)

#添加话题
@main.route('/addtopic', methods=['GET', 'POST'])
@login_required
def add_topic():
    form = AddTopicForm()
    if form.validate_on_submit():
        topic = Topic(name=form.name.data, description=form.description.data)
        db.session.add(topic)
        db.session.commit()
        flash(u'已成功添加话题')
        return redirect(url_for('main.topic_square'))
    return render_template('add_topic.html', form=form)

#话题的动态，按照最新时间排布话题的所有回答
@main.route('/topic/<int:id>/hot')
@login_required
def topic_dynamics(id):
    page = request.args.get('page',1,type=int)
    topic = Topic.query.get_or_404(id)
    pagination = topic.all_answers.paginate(page, per_page=10, error_out=False)
    answers = pagination.items
    return render_template('topic_dynamics.html',pagination=pagination,
                           answers=answers, topic=topic)

#话题下的所有问题
@main.route('/topic/<int:id>/unanswered')
@login_required
def topic_unanswered(id):
    page = request.args.get('page', 1, type=int)
    topic = Topic.query.get_or_404(id)
    pagination = topic.questions.paginate(page, per_page=20, error_out=False)
    questions = pagination.items
    return render_template('topic_unanswered.html', pagination=pagination,
                           questions=questions, topic=topic)

#话题的关注者
@main.route('/topic/<int:id>/followers')
@login_required
def topic_followers(id):
    topic = Topic.query.get_or_404(id)
    return render_template('topic_followers.html', topic=topic)

#提问
@main.route('/asking', methods=['GET', 'POST'])
@login_required
def asking():
    form = AskingForm()
    if not current_user.can(Permission.WRITE_ARTICLES):
        abort(403)
    if form.validate_on_submit():
        question = Question(title=form.title.data,
                    body=form.body.data,
                    author=current_user._get_current_object())
        for topic_id in form.topics.data:
            topic = Topic.query.get(topic_id)
            question.topics.append(topic)
        db.session.add(question)
        db.session.commit()
        flash(u'问题已成功提交')
        return redirect(url_for('main.question', id=question.id))
    return render_template('main/asking.html', form=form)

#单个问题的页面
@main.route('/question/<int:id>', methods=['GET', 'POST'])
@login_required
def question(id):
    form = AnswerForm()
    if not current_user.can(Permission.WRITE_ARTICLES):
        abort(403)
    question = Question.query.get_or_404(id)
    global question_views
    question_views += 1
    if form.validate_on_submit():
        answer = Answer(body=form.body.data,
                        question=question,
                        author=current_user._get_current_object())
        db.session.add(answer)
        db.session.commit()

app/templates/main/_profile.html
{% extends "base.html" %}

{% block title %}{{user.username}} - 知乎{% endblock %}

{% block page_content %}
<div class="page-header">
    <p><img class="img-rounded profile-thumbnail profile-top" src="{{user.gravatar(size=180)}}"/></p>
    <div class="profile-header">
        <p class="content">
            <b class="username">{{user.username}}</b>

                {% if user.gender %}
                    {% if user.gender == 'Male' %}
                    <span class="glyphicon glyphicon-king"></span>
                    {% else%}
                    <span class="glyphicon glyphicon-queen"></span>
                    {% endif %}
                {% endif %}

            {% if user.description %}
            <span class="description">{{user.description}}</span>
            {% endif %}
        </p>
        {% if user.location %}
        <p><b>居住城市   </b><span class="profile-value"> {{user.location}}</span></p><br/>
        {% endif %}
        {% if user.profession %}
        <p><b>所在行业  </b><span class="profile-value">{{user.profession}}</span> </p><br/>
        {% endif %}
        {% if user.working_experience %}
        <p><b>职业经历  </b><span class="profile-value"> {{user.working_experience}}</span></p><br/>
        {% endif %}
        {% if user.education_experience %}
        <p><b>教育经历  </b><span class="profile-value"> {{user.education_experience}}</span></p><br/>
        {% endif %}
        {% if user.about_me %}
        <p><b>个人简介  </b><span class="profile-value"> {{user.about_me}}</span></p>
        {% endif %}


    </div>
</div>
<div>{% block more_info %}{% endblock %}</div>
{% endblock %}

{% block page_side %}
<div class="content">
        <p>
            <a href="{{url_for('main.followings', username=user.username)}}">关注了{{user.followings.count()}}
            </a> | <a href="{{url_for('main.followers', username=user.username)}}">关注者{{user.followers.count()}}</a>
        </p>
        {% if user!=current_user %}
            {% if not current_user.is_following(user) %}
            <a type="button" class="btn btn-primary"
               href="{{url_for('main.follow', username=user.username)}}"> +关注</a>
            {% else %}
            <a type="button" class="btn btn-default"
               href="{{url_for('main.unfollow', username=user.username)}}">取消关注</a>
            {% endif %}
        {% endif %}<br/>
        {% if user==current_user %}
        <a type="button" class="btn btn-info "
           href="{{url_for('main.editprofile')}}">
            编辑个人资料
        </a>
        {% endif %}
</div>
{% endblock %}

app/templates/main/asking.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}提问 - 知乎{% endblock %}

{% block page_content %}
<div class="page-header">
    <p class="zhihu">写下你的问题</p>
    <small>描述清楚的问题更易得到解答</small>
</div>

{{wtf.quick_form(form)}}

{% endblock %}

app/templates/main/editprofile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}编辑个人资料-知乎{% endblock %}

{% block page_content %}
<div class="page-header">
    <img class="img-rounded profile-thumbnail" src="{{current_user.gravatar(size=180)}}"/>
    <div class="profile-header">
        <h1>{{current_user.username}}</h1>
        <div class="col-md-6">
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/followers.html
{% extends "main/_profile.html" %}

{% block more_info %}
<div>
    <ul class="nav nav-tabs">
        <li><a href="{{url_for('main.profile', username=user.username)}}">动态</a> </li>
        <li><a href="{{url_for('main.people_answers',username=user.username)}}">回答{{user.answers.count()}}</a> </li>
        <li><a href="{{url_for('main.people_asks', username=user.username)}}">提问{{user.questions_asked.count()}}</a> </li>
        <li class="active"><a href="{{url_for('main.followers',username=user.username)}}">关注他的人</a> </li>
        <li><a href="{{url_for('main.followings',username=user.username)}}">他关注的人</a> </li>
        <li><a href="{{url_for('main.people_following_topics',username=user.username)}}">关注的话题</a> </li>
        <li><a href="{{url_for('main.people_following_questions',username=user.username)}}">关注的问题</a> </li>
    </ul>
</div>
<div class="profile-top">
    <p><b>关注他的人</b></p>
    {% for follow in user.followers %}
    <a href="{{url_for('main.profile', username=follow.follower.username)}}">
        <img class="img-rounded profile-thumbnail" src="{{follow.follower.gravatar(size=36)}}" />
    </a>
    <div class="answerers">
        <a href="{{url_for('main.profile', username=follow.follower.username)}}">
            {{follow.follower.username}}
        </a>
        {% if current_user != follow.follower %}
            {% if not current_user.is_following(follow.follower) %}
            <a type="button" class="btn btn-primary right"
               href="{{url_for('main.follow', username=follow.follower.username)}}">
                + 关注他
            </a>
            {% else %}
            <a type="button" class="btn btn-default right"
               href="{{url_for('main.unfollow', username=follow.follower.username)}}">
                取消关注
            </a>
            {% endif %}
        {% endif %}
        <p><small>{{follow.follower.description}}</small></p>
    </div><hr/>
    {% endfor %}
</div>
{% endblock %}

app/templates/main/followings.html
{% extends "main/_profile.html" %}

{% block more_info %}
<div>
    <ul class="nav nav-tabs">
        <li><a href="{{url_for('main.profile', username=user.username)}}">动态</a> </li>
        <li><a href="{{url_for('main.people_answers',username=user.username)}}">回答{{user.answers.count()}}</a> </li>
        <li><a href="{{url_for('main.people_asks', username=user.username)}}">提问{{user.questions_asked.count()}}</a> </li>
        <li><a href="{{url_for('main.followers',username=user.username)}}">关注他的人</a> </li>
        <li class="active"><a href="{{url_for('main.followings',username=user.username)}}">他关注的人</a> </li>
        <li><a href="{{url_for('main.people_following_topics',username=user.username)}}">关注的话题</a> </li>
        <li><a href="{{url_for('main.people_following_questions',username=user.username)}}">关注的问题</a> </li>
    </ul>
</div>
<div class="profile-top">
    <p><b>他关注的人</b></p>
    {% for following in user.followings %}
    <a href="{{url_for('main.profile', username=following.followed.username)}}">
        <img class="img-rounded profile-thumbnail" src="{{following.followed.gravatar(size=36)}}" />
    </a>
    <div class="answerers">
        <a href="{{url_for('main.profile', username=following.followed.username)}}">
            {{following.followed.username}}
        </a>
        {% if current_user != following.followed %}
            {% if not current_user.is_following(following.followed) %}
            <a type="button" class="btn btn-primary right"
               href="{{url_for('main.follow', username=following.followed.username)}}">
                + 关注他
            </a>
            {% else %}
            <a type="button" class="btn btn-default right"
               href="{{url_for('main.unfollow', username=following.followed.username)}}">
                取消关注
            </a>
            {% endif %}
        {% endif %}
        <p><small>{{following.followed.description}}</small></p>
    </div><hr/>
    {% endfor %}
</div>
{% endblock %}

app/templates/main/profile_activities.html
{% extends "main/_profile.html" %}
{% import "_macros.html" as macro %}
{% block more_info %}
<div>
    <ul class="nav nav-tabs">
        <li class="active"><a href="{{url_for('main.profile', username=user.username)}}">动态</a> </li>
        <li><a href="{{url_for('main.people_answers',username=user.username)}}">回答{{user.answers.count()}}</a> </li>
        <li><a href="{{url_for('main.people_asks', username=user.username)}}">提问{{user.questions_asked.count()}}</a> </li>
        <li><a href="{{url_for('main.followers',username=user.username)}}">关注他的人</a> </li>
        <li><a href="{{url_for('main.followings',username=user.username)}}">他关注的人</a> </li>
        <li><a href="{{url_for('main.people_following_topics',username=user.username)}}">关注的话题</a> </li>
        <li><a href="{{url_for('main.people_following_questions',username=user.username)}}">关注的问题</a> </li>
    </ul>
</div>
<div>
    {% for like in likes %}
    {% if like.answer %}
    <p class="grey">赞同了回答<span class="right">{{moment(like.timestamp).fromNow(refresh=True)}}</span> </p>
    <p ><a class="black-bold-link" href="{{url_for('main.question', id=like.answer.question.id)}}">
        {{like.answer.question.title}}</a>
    </p>
        {% for answer in [like.answer] %}
        {% include "main/_answer.html" %}
        {% endfor %}
    {% endif %}
    {% endfor %}
    {% if pagination %}
    <div class="pagination">
        {{macro.pagination_widget(pagination, 'main.profile', username=user.username)}}
    </div>
    {% endif %}
</div>
{% endblock %}

app/templates/main/profile_answers.html
{% extends "main/_profile.html" %}
{% import "_macros.html" as macro %}
{% block more_info %}
<div>
    <ul class="nav nav-tabs">
        <li><a href="{{url_for('main.profile', username=user.username)}}">动态</a> </li>
        <li class="active"><a href="{{url_for('main.people_answers',username=user.username)}}">回答{{user.answers.count()}}</a> </li>
        <li><a href="{{url_for('main.people_asks', username=user.username)}}">提问{{user.questions_asked.count()}}</a> </li>
        <li><a href="{{url_for('main.followers',username=user.username)}}">关注他的人</a> </li>
        <li><a href="{{url_for('main.followings',username=user.username)}}">他关注的人</a> </li>
        <li><a href="{{url_for('main.people_following_topics',username=user.username)}}">关注的话题</a> </li>
        <li><a href="{{url_for('main.people_following_questions',username=user.username)}}">关注的问题</a> </li>
    </ul>
</div>
<div class="profile-top">
    {% for answer in answers %}
    <p><a class="black-bold-link" href="{{url_for('main.question', id=answer.question.id)}}">
        {{answer.question.title}}</a>
        <span class="right">{{moment(answer.timestamp).fromNow(refresh=True)}}</span>
    </p>
        {% include "main/_answer.html" %}
    {% endfor %}
    {% if pagination %}
    <div class="pagination">
        {{macro.pagination_widget(pagination, 'main.people_answers', username=user.username)}}
    </div>
    {% endif %}
</div>
{% endblock %}

app/templates/main/profile_questions.html
{% extends "main/_profile.html" %}
{% import "_macros.html" as macro %}
{% block more_info %}
<div>
    <ul class="nav nav-tabs">
        <li><a href="{{url_for('main.profile', username=user.username)}}">动态</a> </li>
        <li><a href="{{url_for('main.people_answers',username=user.username)}}">回答{{user.answers.count()}}</a> </li>
        <li><a href="{{url_for('main.people_asks', username=user.username)}}">提问{{user.questions_asked.count()}}</a> </li>
        <li><a href="{{url_for('main.followers',username=user.username)}}">关注他的人</a> </li>
        <li><a href="{{url_for('main.followings',username=user.username)}}">他关注的人</a> </li>
        <li><a href="{{url_for('main.people_following_topics',username=user.username)}}">关注的话题</a> </li>
        <li class="active"><a href="{{url_for('main.people_following_questions',username=user.username)}}">关注的问题</a> </li>
    </ul>
</div>
<div class="profile-top">
    {% for question in questions %}
    <p><a class="black-bold-link" href="{{url_for('main.question', id=question.id)}}">{{question.title}}</a> </p>
    <p class="grey">{{moment(question.timestamp).format('L')}} * {{question.answers.count()}}个回答 * {{question.followers.count()}}个关注</p>
    <hr/>
    {% endfor %}
    {% if pagination %}
    <div class="pagination">
        {{macro.pagination_widget(pagination, 'main.people_following_questions', username=user.username)}}
    </div>
    {% endif %}
</div>
{% endblock %}

app/templates/main/profile_topics.html
{% extends "main/_profile.html" %}

{% block more_info %}
<div>
    <ul class="nav nav-tabs">
        <li><a href="{{url_for('main.profile', username=user.username)}}">动态</a> </li>
        <li><a href="{{url_for('main.people_answers',username=user.username)}}">回答{{user.answers.count()}}</a> </li>
        <li><a href="{{url_for('main.people_asks', username=user.username)}}">提问{{user.questions_asked.count()}}</a> </li>
        <li><a href="{{url_for('main.followers',username=user.username)}}">关注他的人</a> </li>
        <li><a href="{{url_for('main.followings',username=user.username)}}">他关注的人</a> </li>
        <li class="active"><a href="{{url_for('main.people_following_topics',username=user.username)}}">关注的话题</a> </li>
        <li><a href="{{url_for('main.people_following_questions',username=user.username)}}">关注的问题</a> </li>
    </ul>
</div>
<div class="profile-top">
    {% for topic in topics %}
    <p><a class="black-bold-link" href="{{url_for('main.topic_dynamics', id=topic.id)}}">{{topic.name}}</a> </p>
    <hr/>
    {% endfor %}
</div>
{% endblock %}

app/templates/main/question.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{question.title}} - 知乎 {% endblock %}

{% block page_content %}
<div class="page-header">
    <div>{% for topic in question.topics %}
        <a type="button" class="btn btn-default btn-sm topic-button"
           href="{{url_for('main.topic_dynamics', id=topic.id)}}">
            {{topic.name}}
        </a>
        {% endfor %}
    </div>
    <div>
        <p class="topic-name">{{question.title}}</p>
        <p>{{question.body}}
        {% if current_user == question.author %}
        <a type="button" class="btn btn-danger btn-xs right"
           href="{{url_for('main.delete_question', id=question.id)}}">删除问题</a>
        {% endif %}
        </p>
    </div>
</div>
<div>
    <p class="bold-and-toppad">{{question.answers.count()}}个回答</p><hr/>
    {% for answer in question.answers %}

    {% include "main/_answer.html" %}
    {% endfor %}
</div>
<div>
    <a name="answer"></a>
    {{wtf.quick_form(form)}}
</div>
{% endblock %}
{% block page_side %}
<div class="content right">
    <p style="font-size:larger;"><a target="_blank" href="{{url_for('main.question_followers', id=question.id)}}"> 关注者{{question.followers.count()}}  </a>
        |    被浏览{{question_views}}</p><br/>
    <p>
    <a type="button" class="btn btn-default que-button right" href="#answer">写回答</a>
    {% if current_user.is_following_question(question) %}
    <a type="button" class="btn btn-default" href="{{url_for('main.unfollow_question', id=question.id)}}">
        取消关注
    </a>
    {% else %}
    <a type="button" class="btn btn-primary" href="{{url_for('main.follow_question', id=question.id)}}">
        关注问题
    </a>
    </p>
    {% endif %}

</div>
{% endblock %}

app/templates/main/question_followers.html
{% extends "base.html" %}

{% block title %}关注该问题的人 - {{question.title}} - 知乎 {% endblock %}

{% block page_content %}
<div class="page-header">
    <div>
        <a type="button" class="btn btn-default btn-sm topic-button"
           href="{{url_for('main.topic_dynamics', id=question.topics[0].id)}}">
            {{question.topics[0].name}}
        </a>
    </div>
    <div>
        <a href="{{url_for('main.question', id=question.id)}}">
            <p class="topic-name">{{question.title}}</p>
        </a>
    </div>
</div>
<div>
    {% for follower in question.followers %}
    <a href="{{url_for('main.profile', username=follower.username)}}">
        <img class="img-round profile-thumbnail" src="{{follower.gravatar(size=36)}}" />
    </a>
    <div class="answerers">
    <a style="font-weight:bold;" href="{{url_for('main.profile', username=follower.username)}}">{{follower.username}}</a>
    <div class="right">
        {% if current_user != follower %}
        {% if current_user.is_following(follower) %}
        <a type="button" class="btn btn-default btn-xs"
           href="{{url_for('main.unfollow', username=follower.username)}}">取消关注</a>
        {% else %}
        <a type="button" class="btn btn-success btn-xs"
           href="{{url_for('main.follow', username=follower.username)}}">+ 关注</a>
        {% endif %}
        {% endif %}
    </div>
        <p style="font-size:smaller;">{{follower.description}}</p>
    </div><hr/>
    {% endfor %}
</div>
{% endblock %}